# based on example file for maven projects:
# https://gitlab.com/gitlab-org/gitlab-ci-yml/blob/master/Maven.gitlab-ci.yml

image: maven:3.6.1-jdk-8

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

cache:
  paths:
    - .m2/repository/
    - .local/

stages:
  - test
  - build
  - docker

before_script:
  - env
  - which java
  - java -version

verify_java:
  except:
    - schedules
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean verify
    - mvn $MAVEN_CLI_OPTS clean test-compile

checkstyle:
  except:
    - schedules
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS clean checkstyle:checkstyle'

integration_test:
  only:
    - schedules
  script:
    - if [ ! -f ".local/apache-jmeter-5.1.1.tgz" ]; then mkdir .local && wget "https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.1.1.tgz" -O .local/apache-jmeter-5.1.1.tgz; fi
    - tar xf .local/apache-jmeter-5.1.1.tgz
    - cd integration-tests
    - bash ../apache-jmeter-5.1.1/bin/jmeter.sh -n -t RIESGOS-integration-tests.jmx -o jmeter-report -l jmeter-log.txt -e
    - cat jmeter-log.txt
    - if [ "$(fgrep -c 'Test failed' jmeter-log.txt)" != "0" ]; then false; else true; fi
  artifacts:
    name: jmeter-report
    paths:
      - ${CI_PROJECT_DIR}/integration-tests/jmeter-report

dockerbuild:
  stage: docker
  image: docker:19.03.1
  before_script: []
  cache: {}
  except:
    - schedules
  script:
    - docker build -f assistance/Dockerfile .
