version: "3"

services:
  quakeledger:
    image: gfzriesgos/quakeledger:latest

  shakyground:
    image: gfzriesgos/shakyground:latest

  assetmaster:
    image: gfzriesgos/assetmaster:latest

  modelprop:
    image: gfzriesgos/modelprop:latest

  deus:
    image: gfzriesgos/deus:latest

  flooddamage:
    image: gfzriesgos/flooddamage:latest

  riesgos-wps:
    build:
      context: ../
      dockerfile: assistance/Dockerfile
    container_name: riesgos-wps-dev
    ports:
      - "8080:8080"
    volumes:
      - "riesgos-json-config-dev:/usr/share/riesgos/json-configurations"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "riesgos-wps-hsqldb-dev:/usr/local/tomcat/webapps/wps/WEB-INF/classes/db/data"
      - "../target/gfz-riesgos-wps-1.0-SNAPSHOT.jar:/usr/local/tomcat/webapps/wps/WEB-INF/lib/gfz-riesgos-wps.jar"

volumes:
  riesgos-json-config-dev:
  riesgos-wps-hsqldb-dev:
