version: "3"

services:
  quakeledger:
    image: gfzriesgos/quakeledger:1.0

  shakyground:
    image: gfzriesgos/shakyground:1.0

  assetmaster:
    image: gfzriesgos/assetmaster:1.0

  modelprop:
    image: gfzriesgos/modelprop:1.0

  deus:
    image: gfzriesgos/deus:1.0

  flooddamage:
    image: gfzriesgos/flooddamage:20191122

  riesgos-wps:
    image: gfzriesgos/riesgos-wps:__PROD_IMAGE_TAG__
    container_name: riesgos-wps-prod
    restart: always
    environment:
      - CATALINA_OPTS=-Xmx12g -Xms12g
    ports:
      - "80:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "riesgos-json-config:/usr/share/riesgos/json-configurations"
      - "riesgos-wps-hsqldb:/usr/local/tomcat/webapps/wps/WEB-INF/classes/db/data"
      - "riesgos-wps-logs:/usr/local/tomcat/logs"
      - "${PWD}/tomcat-users-prod.xml:/usr/local/tomcat/conf/tomcat-users.xml"
      - "${PWD}/users-prod.xml:/usr/local/tomcat/webapps/geoserver/data/security/usergroup/default/users.xml"
      - "${PWD}/application_properties_prod.js:/usr/local/tomcat/webapps/wps-js-client/application_properties.js"

volumes:
  riesgos-json-config:
  riesgos-wps-hsqldb:
  riesgos-wps-logs:
